using System.Windows.Input;

using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.DependencyInjection;
using CommunityToolkit.Mvvm.Input;

using LiveFootball.Core.Helpers;
using LiveFootball.Core.Services;

using Newtonsoft.Json.Linq;

namespace LiveFootball.Core.ViewModels;

public partial class MenuViewModel : ObservableObject
{
    #region Properties

    private readonly IFootballApiService _footballService;
    private readonly IDeserializationService _deserializeDataService;

    private CancellationTokenSource _fetchLiveGamesDataCancellationTokenSource = null!;

    [ObservableProperty] 
    private List<MenuItemViewModel> _leagues;
    
    [ObservableProperty] 
    private bool _isLoading;

    #endregion

    #region Constructors

    public MenuViewModel(IFootballApiService? footballApiService = null,
                         IDeserializationService? deserializeDataService = null)
    {
        _footballService = footballApiService ?? Ioc.Default.GetRequiredService<IFootballApiService>();
        _deserializeDataService =
            deserializeDataService ?? Ioc.Default.GetRequiredService<IDeserializationService>(); 

        Leagues = new List<MenuItemViewModel>
        {
            new("World Cup", "1"),
new("UEFA Champions League", "2"),
new("UEFA Europa League", "3"),
new("Euro Championship", "4"),
new("UEFA Nations League", "5"),
new("Africa Cup of Nations", "6"),
new("Asian Cup", "7"),
new("World Cup - Women", "8"),
new("Copa America", "9"),
new("Friendlies", "10"),
new("CONMEBOL Sudamericana", "11"),
new("CAF Champions League", "12"),
new("CONMEBOL Libertadores", "13"),
new("UEFA Youth League", "14"),
new("FIFA Club World Cup", "15"),
new("CONCACAF Champions League", "16"),
new("AFC Champions League", "17"),
new("AFC Cup", "18"),
new("African Nations Championship", "19"),
new("CAF Confederation Cup", "20"),
new("Confederations Cup", "21"),
new("CONCACAF Gold Cup", "22"),
new("EAFF E-1 Football Championship", "23"),
new("AFF Championship", "24"),
new("Gulf Cup of Nations", "25"),
new("International Champions Cup", "26"),
new("OFC Champions League", "27"),
new("SAFF Championship", "28"),
new("World Cup - Qualification Africa", "29"),
new("World Cup - Qualification Asia", "30"),
new("World Cup - Qualification CONCACAF", "31"),
new("World Cup - Qualification Europe", "32"),
new("World Cup - Qualification Oceania", "33"),
new("World Cup - Qualification South America", "34"),
new("Asian Cup - Qualification", "35"),
new("Africa Cup of Nations - Qualification", "36"),
new("World Cup - Qualification Intercontinental Play-offs", "37"),
new("UEFA U21 Championship", "38"),
new("Premier League", "39"),
new("Championship", "40"),
new("League One", "41"),
new("League Two", "42"),
new("National League", "43"),
new("FA WSL", "44"),
new("FA Cup", "45"),
new("EFL Trophy", "46"),
new("FA Trophy", "47"),
new("League Cup", "48"),
new("National League - Play-offs", "49"),
new("National League - North", "50"),
new("National League - South", "51"),
new("Non League Div One - Isthmian North", "52"),
new("Non League Div One - Isthmian South Central", "53"),
new("Non League Div One - Northern West", "54"),
new("Non League Div One - Northern Midlands", "55"),
new("Non League Div One - Southern South", "56"),
new("Non League Div One - Isthmian South East", "57"),
new("Non League Premier - Isthmian", "58"),
new("Non League Premier - Northern", "59"),
new("Non League Premier - Southern South", "60"),
new("Ligue 1", "61"),
new("Ligue 2", "62"),
new("National 1", "63"),
new("Feminine Division 1", "64"),
new("Coupe de la Ligue", "65"),
new("Coupe de France", "66"),
new("National 2 - Group A", "67"),
new("National 2 - Group B", "68"),
new("National 2 - Group C", "69"),
new("National 2 - Group D", "70"),
new("Serie A", "71"),
new("Serie B", "72"),
new("Copa Do Brasil", "73"),
new("Brasileiro Women", "74"),
new("Serie C", "75"),
new("Serie D", "76"),
new("Alagoano", "77"),
new("Bundesliga", "78"),
new("2. Bundesliga", "79"),
new("3. Liga", "80"),
new("DFB Pokal", "81"),
new("Frauen Bundesliga", "82"),
new("Regionalliga - Bayern", "83"),
new("Regionalliga - Nord", "84"),
new("Regionalliga - Nordost", "85"),
new("Regionalliga - SudWest", "86"),
new("Regionalliga - West", "87"),
new("Eredivisie", "88"),
new("Eerste Divisie", "89"),
new("KNVB Beker", "90"),
new("Eredivisie Women", "91"),
new("Derde Divisie - Saturday", "92"),
new("Derde Divisie - Sunday", "93"),
new("Primeira Liga", "94"),
new("Segunda Liga", "95"),
new("Taça de Portugal", "96"),
new("Taça da Liga", "97"),
new("J1 League", "98"),
new("J2 League", "99"),
new("J3 League", "100"),
new("J-League Cup", "101"),
new("Emperor Cup", "102"),
new("Eliteserien", "103"),
new("1. Division", "104"),
new("NM Cupen", "105"),
new("Ekstraklasa", "106"),
new("I Liga", "107"),
new("Cup", "108"),
new("II Liga - East", "109"),
new("Premier League", "110"),
new("FAW Championship", "111"),
new("Welsh Cup", "112"),
new("Allsvenskan", "113"),
new("Superettan", "114"),
new("Svenska Cupen", "115"),
new("Premier League", "116"),
new("1. Division", "117"),
new("2. Division", "118"),
new("Superliga", "119"),
new("1. Division", "120"),
new("DBU Pokalen", "121"),
new("2nd Division - Group 1", "122"),
new("2nd Division - Group 2", "123"),
new("Denmark Series - Group 1", "124"),
new("Denmark Series - Group 2", "125"),
new("Denmark Series - Group 3", "126"),
new("Denmark Series - Group 4", "127"),
new("Liga Profesional Argentina", "128"),
new("Primera Nacional", "129"),
new("Copa Argentina", "130"),
new("Primera B Metropolitana", "131"),
new("Primera C", "132"),
new("Primera D", "133"),
new("Torneo Federal A", "134"),
new("Serie A", "135"),
new("Serie B", "136"),
new("Coppa Italia", "137"),
new("Serie C - Girone A", "138"),
new("Serie A Women", "139"),
new("La Liga", "140"),
new("Segunda División", "141"),
new("Primera División Femenina", "142"),
new("Copa del Rey", "143"),
new("Jupiler Pro League", "144"),
new("Challenger Pro League", "145"),
new("Super League Women", "146"),
new("Cup", "147"),
new("Second Amateur Division - ACFF", "148"),
new("Second Amateur Division - VFV A", "149"),
new("Second Amateur Division - VFV B", "150"),
new("Third Amateur Division - VFV A", "151"),
new("Third Amateur Division - VFV B", "152"),
new("Provincial - Antwerpen", "153"),
new("Provincial - Brabant VFV", "154"),
new("Provincial - Hainaut", "155"),
new("Provincial - Liege", "156"),
new("Provincial - Limburg", "157"),
new("Provincial - Luxembourg", "158"),
new("Provincial - Namur", "159"),
new("Provincial - Oost-Vlaanderen", "160"),
new("Provincial - West-Vlaanderen", "161"),
new("Primera División", "162"),
new("Liga de Ascenso", "163"),
new("Úrvalsdeild", "164"),
new("1. Deild", "165"),
new("2. Deild", "166"),
new("Cup", "167"),
new("League Cup", "168"),
new("Super League", "169"),
new("League One", "170"),
new("FA Cup", "171"),
new("First League", "172"),
new("Second League", "173"),
new("Cup", "174"),
new("Third League - Northeast", "175"),
new("Third League - Northwest", "176"),
new("Third League - Southeast", "177"),
new("Third League - Southwest", "178"),
new("Premiership", "179"),
new("Championship", "180"),
new("FA Cup", "181"),
new("Challenge Cup", "182"),
new("League One", "183"),
new("League Two", "184"),
new("League Cup", "185"),
new("Ligue 1", "186"),
new("Ligue 2", "187"),
new("A-League", "188"),
new("Capital Territory NPL", "189"),
new("A-League Women", "190"),
new("Brisbane Premier League", "191"),
new("New South Wales NPL", "192"),
new("Northern Territory Premier League", "193"),
new("South Australia NPL", "194"),
new("Victoria NPL", "195"),
new("Western Australia NPL", "196"),
new("Super League 1", "197"),
new("Football League", "198"),
new("Cup", "199"),
new("Botola Pro", "200"),
new("Botola 2", "201"),
new("Ligue 1", "202"),
new("Süper Lig", "203"),
new("1. Lig", "204"),
new("2. Lig", "205"),
new("Cup", "206"),
new("Super League", "207"),
new("Challenge League", "208"),
new("Schweizer Cup", "209"),
new("HNL", "210"),
new("First NL", "211"),
new("Cup", "212"),
new("Third NL - Istok", "213"),
new("Third NL - Jug", "214"),
new("Third NL - Sjever", "215"),
new("Third NL - Sredite", "216"),
new("Third NL - Zapad", "217"),
new("Bundesliga", "218"),
new("2. Liga", "219"),
new("Cup", "220"),
new("Regionalliga - Ost", "221"),
new("Regionalliga - Mitte", "222"),
new("Regionalliga - West", "223"),
new("Landesliga - Burgenland", "224"),
new("Landesliga - Karnten", "225"),
new("Landesliga - Niederosterreich", "226"),
new("Landesliga - Oberosterreich", "227"),
new("Landesliga - Salzburg", "228"),
new("Landesliga - Steiermark", "229"),
new("Landesliga - Tirol", "230"),
new("Landesliga - Vorarlbergliga", "231"),
new("Landesliga - Wien", "232"),
new("Premier League", "233"),
new("Liga Nacional", "234"),
new("Premier League", "235"),
new("First League", "236"),
new("Cup", "237"),
new("Youth Championship", "238"),
new("Primera A", "239"),
new("Primera B", "240"),
new("Copa Colombia", "241"),
new("Liga Pro", "242"),
new("Liga Pro Serie B", "243"),
new("Veikkausliiga", "244"),
new("Ykkönen", "245"),
new("Suomen Cup", "246"),
new("Kakkonen - Lohko A", "247"),
new("Kakkonen - Lohko B", "248"),
new("Kakkonen - Lohko C", "249"),
new("Division Profesional - Apertura", "250"),
new("Division Intermedia", "251"),
new("Division Profesional - Clausura", "252"),
new("Major League Soccer", "253"),
new("NWSL Women", "254"),
new("USL Championship", "255"),
new("USL League Two", "256"),
new("US Open Cup", "257"),
new("Canadian Soccer League", "258"),
new("Canadian Championship", "259"),
new("Pacific Coast Soccer League", "260"),
new("National Division", "261"),
new("Liga MX", "262"),
new("Liga de Expansión MX", "263"),
new("Copa MX", "264"),
new("Primera División", "265"),
new("Primera B", "266"),
new("Copa Chile", "267"),
new("Primera División - Apertura", "268"),
new("Segunda División", "269"),
new("Primera División - Clausura", "270"),
new("NB I", "271"),
new("NB II", "272"),
new("Magyar Kupa", "273"),
new("Liga 1", "274"),
new("Liga 2", "275"),
new("FKF Premier League", "276"),
new("Super League", "277"),
new("Super League", "278"),
new("Premier League", "279"),
new("Premiership", "280"),
new("Primera División", "281"),
new("Segunda División", "282"),
new("Liga I", "283"),
new("Liga II", "284"),
new("Cupa României", "285"),
new("Super Liga", "286"),
new("Prva Liga", "287"),
new("Premier Soccer League", "288"),
new("1st Division", "289"),
new("Persian Gulf Pro League", "290"),
new("Azadegan League", "291"),
new("K League 1", "292"),
new("K League 2", "293"),
new("FA Cup", "294"),
new("K3 League", "295"),
new("Thai League 1", "296"),
new("Thai League 2", "297"),
new("FA Cup", "298"),
new("Primera División", "299"),
new("Segunda División", "300"),
new("Pro League", "301"),
new("League Cup", "302"),
new("Division 1", "303"),
new("Liga Panameña de Fútbol", "304"),
new("Stars League", "305"),
new("Second Division", "306"),
new("Pro League", "307"),
new("Division 1", "308"),
new("Division 2", "309"),
new("Superliga", "310"),
new("1st Division", "311"),
new("1a Divisió", "312"),
new("2a Divisió", "313"),
new("Cup", "314"),
new("Premijer Liga", "315"),
new("1st League - FBiH", "316"),
new("1st League - RS", "317"),
new("1. Division", "318"),
new("2. Division", "319"),
new("3. Division", "320"),
new("Cup", "321"),
new("Premier League", "322"),
new("Indian Super League", "323"),
new("I-League", "324"),
new("Santosh Trophy", "325"),
new("Erovnuli Liga 2", "326"),
new("Erovnuli Liga", "327"),
new("Esiliiga A", "328"),
new("Meistriliiga", "329"),
new("Premier League", "330"),
new("Division 1", "331"),
new("Super Liga", "332"),
new("Premier League", "333"),
new("Persha Liga", "334"),
new("Cup", "335"),
new("Druha Liga", "336"),
new("Druha Liga - Group B", "337"),
new("Primera Division", "338"),
new("Liga Nacional", "339"),
new("V.League 1", "340"),
new("Cup", "341"),
new("Premier League", "342"),
new("First League", "343"),
new("Primera División", "344"),
new("Czech Liga", "345"),
new("FNL", "346"),
new("Cup", "347"),
new("3. liga - CFL A", "348"),
new("3. liga - MSFL", "349"),
new("4. liga - Divizie A", "350"),
new("4. liga - Divizie B", "351"),
new("4. liga - Divizie C", "352"),
new("4. liga - Divizie D", "353"),
new("4. liga - Divizie E", "354"),
new("First League", "355"),
new("Second League", "356"),
new("Premier Division", "357"),
new("First Division", "358"),
new("FAI Cup", "359"),
new("League Cup", "360"),
new("1 Lyga", "361"),
new("A Lyga", "362"),
new("Premier League", "363"),
new("1. Liga", "364"),
new("Virsliga", "365"),
new("1. Deild", "366"),
new("Meistaradeildin", "367"),
new("Premier League", "368"),
new("Super League", "369"),
new("Primera Division", "370"),
new("First League", "371"),
new("Second League", "372"),
new("1. SNL", "373"),
new("2. SNL", "374"),
new("Cup", "375"),
new("National Football League", "376"),
new("Division d'Honneur", "377"),
new("Ligue 1", "378"),
new("Ligue Haïtienne", "379"),
new("Premier League", "380"),
new("HKFA 1st Division", "381"),
new("Liga Leumit", "382"),
new("Ligat Ha'al", "383"),
new("State Cup", "384"),
new("Toto Cup Ligat Al", "385"),
new("Ligue 1", "386"),
new("League", "387"),
new("1. Division", "388"),
new("Premier League", "389"),
new("Premier League", "390"),
new("Super League", "391"),
new("Challenge League", "392"),
new("Premier League", "393"),
new("Super Liga", "394"),
new("Liga 1", "395"),
new("Primera Division", "396"),
new("Girabola", "397"),
new("Premier League", "398"),
new("NPFL", "399"),
new("Super League", "400"),
new("Premier Soccer League", "401"),
new("Sudani Premier League", "402"),
new("Ligue 1", "403"),
new("Campionato", "404"),
new("National Soccer League", "405"),
new("Professional League", "406"),
new("Championship", "407"),
new("Premiership", "408"),
new("Premier League", "409"),
new("C-League", "410"),
new("Elite One", "411"),
new("Premier League", "412"),
new("Super League", "413"),
new("Premier League", "414"),
new("Championnat National", "415"),
new("Premier League", "416"),
new("Premier League", "417"),
new("Birinci Dasta", "418"),
new("Premyer Liqa", "419"),
new("Cup", "420"),
new("Division di Honor", "421"),
new("Premier League", "422"),
new("Ligue 1", "423"),
new("Ligue 1", "424"),
new("Premier League", "425"),
new("Serie D - Girone A", "426"),
new("Serie D - Girone B", "427"),
new("Serie D - Girone C", "428"),
new("Serie D - Girone D", "429"),
new("Serie D - Girone E", "430"),
new("Serie D - Girone F", "431"),
new("Serie D - Girone G", "432"),
new("Serie D - Girone H", "433"),
new("Serie D - Girone I", "434"),
new("Primera División RFEF - Group 1", "435"),
new("Primera División RFEF - Group 2", "436"),
new("Primera División RFEF - Group 3", "437"),
new("Primera División RFEF - Group 4", "438"),
new("Tercera División RFEF - Group 1", "439"),
new("Tercera División RFEF - Group 2", "440"),
new("Tercera División RFEF - Group 3", "441"),
new("Tercera División RFEF - Group 4", "442"),
new("Tercera División RFEF - Group 5", "443"),
new("Tercera División RFEF - Group 6", "444"),
new("Tercera División RFEF - Group 7", "445"),
new("Tercera División RFEF - Group 8", "446"),
new("Tercera División RFEF - Group 9", "447"),
new("Tercera División RFEF - Group 10", "448"),
new("Tercera División RFEF - Group 11", "449"),
new("Tercera División RFEF - Group 12", "450"),
new("Tercera División RFEF - Group 13", "451"),
new("Tercera División RFEF - Group 14", "452"),
new("Tercera División RFEF - Group 15", "453"),
new("Tercera División RFEF - Group 16", "454"),
new("Tercera División RFEF - Group 17", "455"),
new("Tercera División RFEF - Group 18", "456"),
new("Campeonato de Portugal Prio - Group A", "457"),
new("Campeonato de Portugal Prio - Group B", "458"),
new("Campeonato de Portugal Prio - Group C", "459"),
new("Campeonato de Portugal Prio - Group D", "460"),
new("National 3 - Group A", "461"),
new("National 3 - Group B", "462"),
new("National 3 - Group C", "463"),
new("National 3 - Group D", "464"),
new("National 3 - Group E", "465"),
new("National 3 - Group F", "466"),
new("National 3 - Group H", "467"),
new("National 3 - Group I", "468"),
new("National 3 - Group J", "469"),
new("National 3 - Group K", "470"),
new("National 3 - Group L", "471"),
new("National 3 - Group M", "472"),
new("2. Division - Group 1", "473"),
new("2. Division - Group 2", "474"),
new("Paulista - A1", "475"),
new("Paulista - A2", "476"),
new("Gaúcho - 1", "477"),
new("Gaúcho - 2", "478"),
new("Canadian Premier League", "479"),
new("Olympics Men", "480"),
new("Northern NSW NPL", "481"),
new("Queensland NPL", "482"),
new("Copa de la Superliga", "483"),
new("Frauenliga", "484"),
new("Federation Cup", "485"),
new("Coppa", "486"),
new("First Amateur Division", "487"),
new("U19 Bundesliga", "488"),
new("USL League One", "489"),
new("World Cup - U20", "490"),
new("Løgmanssteypid", "491"),
new("Tweede Divisie", "492"),
new("UEFA U19 Championship", "493"),
new("Super League 2", "494"),
new("Hazfi Cup", "495"),
new("Liga Alef", "496"),
new("Japan Football League", "497"),
new("Cup", "498"),
new("Malaysia Cup", "499"),
new("FA Cup", "500"),
new("Copa Paraguay", "501"),
new("Copa Bicentenario", "502"),
new("Copa Perú", "503"),
new("King's Cup", "504"),
new("League Cup", "505"),
new("2. liga", "506"),
new("Cup", "507"),
new("League Cup", "508"),
new("8 Cup", "509"),
new("1. Liga Promotion", "510"),
new("Cup", "511"),
new("2nd Division - Group A", "512"),
new("2nd Division - Group B", "513"),
new("Coupe Nationale", "514"),
new("U21 League 1", "515"),
new("Super Cup", "516"),
new("Trofeo de Campeones de la Superliga", "517"),
new("Reserve Pro League", "518"),
new("Super Cup", "519"),
new("Acreano", "520"),
new("Amapaense", "521"),
new("Amazonense", "522"),
new("NISA", "523"),
new("Olympics Women", "524"),
new("UEFA Champions League Women", "525"),
new("Trophée des Champions", "526"),
new("Super Cup", "527"),
new("Community Shield", "528"),
new("Super Cup", "529"),
new("Super Cup", "530"),
new("UEFA Super Cup", "531"),
new("AFC U23 Asian Cup", "532"),
new("CAF Super Cup", "533"),
new("CONCACAF Caribbean Club Shield", "534"),
new("CECAFA Senior Challenge Cup", "535"),
new("CONCACAF Nations League", "536"),
new("CONCACAF U20", "537"),
new("Africa Cup of Nations U20", "538"),
new("Super Cup", "539"),
new("CONMEBOL Libertadores U20", "540"),
new("CONMEBOL Recopa", "541"),
new("Iraqi League", "542"),
new("Super Cup", "543"),
new("FA Cup", "544"),
new("AIFF Super Cup", "545"),
new("FAI President's Cup", "546"),
new("Super Cup", "547"),
new("Super Cup", "548"),
new("Damallsvenskan", "549"),
new("Super Cup", "550"),
new("Super Cup", "551"),
new("3. Lig - Group 1", "552"),
new("3. Lig - Group 2", "553"),
new("3. Lig - Group 3", "554"),
new("Supercupa", "555"),
new("Super Cup", "556"),
new("Super Cup", "557"),
new("Supercopa", "558"),
new("League Cup", "559"),
new("Presidents Cup", "560"),
new("Premier Intermediate League", "561"),
new("Reserve League", "562"),
new("Ettan - Norra", "563"),
new("Ettan - Södra", "564"),
new("Liga Primera U20", "565"),
new("Ligue A", "566"),
new("Ligi kuu Bara", "567"),
new("Eerste Divisie", "568"),
new("Premier League", "569"),
new("Premier League", "570"),
new("Vysshaya Liga", "571"),
new("Srpska Liga - Belgrade", "572"),
new("Srpska Liga - Vojvodina", "573"),
new("Srpska Liga - East", "574"),
new("Srpska Liga - West", "575"),
new("Gamma Ethniki - Group 1", "576"),
new("Gamma Ethniki - Group 2", "577"),
new("Gamma Ethniki - Group 3", "578"),
new("Gamma Ethniki - Group 4", "579"),
new("Gamma Ethniki - Group 5", "580"),
new("Gamma Ethniki - Group 6", "581"),
new("Gamma Ethniki - Group 7", "582"),
new("Gamma Ethniki - Group 8", "583"),
new("Premier League", "584"),
new("Premier League", "585"),
new("West Bank Premier League", "586"),
new("World Cup - U17", "587"),
new("National League", "588"),
new("Taiwan Football Premier League", "589"),
new("A Division", "590"),
new("Pro League", "591"),
new("Division 2 - Norra Götaland", "592"),
new("Division 2 - Norra Svealand", "593"),
new("Division 2 - Norrland", "594"),
new("Division 2 - Södra Svealand", "595"),
new("Division 2 - Västra Götaland", "596"),
new("Division 2 - Östra Götaland", "597"),
new("Première Division", "598"),
new("1. Liga Classic - Group 1", "599"),
new("1. Liga Classic - Group 2", "600"),
new("1. Liga Classic - Group 3", "601"),
new("Baiano - 1", "602"),
new("Paraibano", "603"),
new("Catarinense - 1", "604"),
new("Paulista - A3", "605"),
new("Paranaense - 1", "606"),
new("Roraimense", "607"),
new("Maranhense", "608"),
new("Cearense - 1", "609"),
new("Brasiliense", "610"),
new("Capixaba", "611"),
new("Copa do Nordeste", "612"),
new("Baiano - 2", "613"),
new("Paranaense - 2", "614"),
new("Rondoniense", "615"),
new("Potiguar", "616"),
new("Copa do Brasil U20", "617"),
new("São Paulo Youth Cup", "618"),
new("Mineiro - 2", "619"),
new("Cearense - 2", "620"),
new("Piauiense", "621"),
new("Pernambucano - 1", "622"),
new("Sul-Matogrossense", "623"),
new("Carioca - 1", "624"),
new("Carioca - 2", "625"),
new("Sergipano", "626"),
new("Paraense", "627"),
new("Goiano - 1", "628"),
new("Mineiro - 1", "629"),
new("Matogrossense", "630"),
new("Tocantinense", "631"),
new("Supercopa do Brasil", "632"),
new("NB III - Northeast", "633"),
new("NB III - Southwest", "634"),
new("NB III - Northwest", "635"),
new("Ýokary Liga", "636"),
new("V.League 2", "637"),
new("Kvindeliga", "638"),
new("Super Cup", "639"),
new("Kansallinen Liiga", "640"),
new("NWSL Women - Challenge Cup", "641"),
new("Curaçao Sekshon Pagá", "642"),
new("3. liga - Bratislava", "643"),
new("3. liga - West", "644"),
new("3. liga - East", "645"),
new("3. liga - Center", "646"),
new("Lao League", "647"),
new("Tasmania NPL", "648"),
new("Supreme Division Women", "649"),
new("Second League - Group 3", "650"),
new("Second League - Group 1", "651"),
new("Second League - Group 2", "652"),
new("Second League - Group 4", "653"),
new("Super Cup", "654"),
new("Copa Constitució", "655"),
new("Super Cup", "656"),
new("Cup", "657"),
new("Cup", "658"),
new("Super Cup", "659"),
new("WK-League", "660"),
new("Cup", "661"),
new("Copa por México", "662"),
new("Super Cup", "663"),
new("Superliga", "664"),
new("Cup", "665"),
new("Friendlies Women", "666"),
new("Friendlies Clubs", "667"),
new("1. Liga U19", "668"),
new("1. Liga Women", "669"),
new("Community Shield Women", "670"),
new("Úrvalsdeild Women", "671"),
new("David Kipiani Cup", "672"),
new("Liga MX Femenil", "673"),
new("Cupa", "674"),
new("U21 Divisie 1", "675"),
new("Central Youth League", "676"),
new("QSL Cup", "677"),
new("Super Cup", "678"),
new("U21 League", "679"),
new("Cup", "680"),
new("Campeonato de Portugal Prio - Group E", "681"),
new("Campeonato de Portugal Prio - Group F", "682"),
new("Campeonato de Portugal Prio - Group G", "683"),
new("Campeonato de Portugal Prio - Group H", "684"),
new("3. liga - CFL B", "685"),
new("4. liga - Divizie F", "686"),
new("Regionalliga - Tirol", "687"),
new("Regionalliga - Salzburg", "688"),
new("Third Amateur Division - ACFF A", "689"),
new("Third Amateur Division - ACFF B", "690"),
new("Provincial - Brabant ACFF", "691"),
new("Primera División RFEF - Group 5", "692"),
new("Gamma Ethniki - Group 9", "693"),
new("Gamma Ethniki - Group 10", "694"),
new("U18 Premier League - North", "695"),
new("U18 Premier League - South", "696"),
new("WSL Cup", "697"),
new("FA Women's Cup", "698"),
new("Women's Championship", "699"),
new("Kakkosen Cup", "700"),
new("Liga Revelação U23", "701"),
new("Premier League 2 Division One", "702"),
new("Professional Development League", "703"),
new("Coppa Italia Primavera", "704"),
new("Campionato Primavera - 1", "705"),
new("Campionato Primavera - 2", "706"),
new("Cup", "707"),
new("Super Cup", "708"),
new("Cup", "709"),
new("Nacional B", "710"),
new("Segunda División", "711"),
new("Liga Femenina", "712"),
new("Superliga", "713"),
new("Cup", "714"),
new("DFB Junioren Pokal", "715"),
new("Senior Shield", "716"),
new("I-League - 2nd Division", "717"),
new("Piala Indonesia", "718"),
new("Super Cup", "719"),
new("Emir Cup", "720"),
new("Cup", "721"),
new("Liga Premier Serie A", "722"),
new("Cup", "723"),
new("U18 Divisie 1", "724"),
new("Toppserien", "725"),
new("Sultan Cup", "726"),
new("Super Cup", "727"),
new("Liga 1 Feminin", "728"),
new("Coppa Titano", "729"),
new("Football League - Highland League", "730"),
new("Football League - Lowland League", "731"),
new("Cup", "732"),
new("I Liga - Women", "733"),
new("Diski Challenge", "734"),
new("Copa Federacion", "735"),
new("Elitettan", "736"),
new("Svenska Cupen - Women", "737"),
new("League Cup", "738"),
new("AXA Women’s Super League", "739"),
new("CBF Brasileiro U20", "740"),
new("Brasileiro de Aspirantes", "741"),
new("Copa Paulista", "742"),
new("UEFA Championship - Women", "743"),
new("Oberliga - Schleswig-Holstein", "744"),
new("Oberliga - Hamburg", "745"),
new("Oberliga - Mittelrhein", "746"),
new("Oberliga - Westfalen", "747"),
new("Oberliga - Niedersachsen", "748"),
new("Oberliga - Bremen", "749"),
new("Oberliga - Hessen", "750"),
new("Oberliga - Niederrhein", "751"),
new("Oberliga - Rheinland-Pfalz / Saar", "752"),
new("Oberliga - Baden-Württemberg", "753"),
new("Oberliga - Nordost-Nord", "754"),
new("Oberliga - Nordost-Süd", "755"),
new("Cup", "756"),
new("Irish Cup", "757"),
new("Premier Division", "758"),
new("Liga Mayor", "759"),
new("LFA First Division", "760"),
new("Cup", "761"),
new("Premier League", "762"),
new("Mauritian League", "763"),
new("Premier League", "764"),
new("PFL", "765"),
new("China Cup", "766"),
new("CONCACAF League", "767"),
new("Arab Club Champions Cup", "768"),
new("Premier League Asia Trophy", "769"),
new("Pacific Games", "770"),
new("COSAFA U20 Championship", "771"),
new("Leagues Cup", "772"),
new("Sudamericano U20", "773"),
new("3. Division - Girone 1", "774"),
new("3. Division - Girone 2", "775"),
new("3. Division - Girone 3", "776"),
new("3. Division - Girone 4", "777"),
new("3. Division - Girone 5", "778"),
new("3. Division - Girone 6", "779"),
new("III Liga - Group 1", "780"),
new("III Liga - Group 2", "781"),
new("III Liga - Group 3", "782"),
new("III Liga - Group 4", "783"),
new("Liga III - Serie 1", "784"),
new("Liga III - Serie 2", "785"),
new("Liga III - Serie 3", "786"),
new("Liga III - Serie 4", "787"),
new("Liga III - Serie 5", "788"),
new("Liga III - Serie 6", "789"),
new("Liga III - Serie 7", "790"),
new("Liga III - Serie 8", "791"),
new("Liga III - Serie 9", "792"),
new("Liga III - Serie 10", "793"),
new("3. SNL - East", "794"),
new("3. SNL - West", "795"),
new("2. Liga Interregional - Group 1", "796"),
new("2. Liga Interregional - Group 2", "797"),
new("2. Liga Interregional - Group 3", "798"),
new("2. Liga Interregional - Group 4", "799"),
new("2. Liga Interregional - Group 5", "800"),
new("2. Liga Interregional - Group 6", "801"),
new("Cup", "802"),
new("Asian Games", "803"),
new("Caribbean Cup", "804"),
new("Copa Centroamericana", "805"),
new("OFC Nations Cup", "806"),
new("AFC Challenge Cup", "807"),
new("CONCACAF Nations League - Qualification", "808"),
new("Super Cup", "809"),
new("Super Copa", "810"),
new("Federation Cup", "811"),
new("Super Cup", "812"),
new("Elite Two", "813"),
new("Reykjavik Cup", "814"),
new("Fotbolti.net Cup A", "815"),
new("Shield Cup", "816"),
new("Super Cup Primavera", "817"),
new("Super Cup", "818"),
new("Super Cup", "819"),
new("Crown Prince Cup", "820"),
new("FA Trophy", "821"),
new("Cup", "822"),
new("Nasjonal U19 Champions League", "823"),
new("Emir Cup", "824"),
new("Qatar Cup", "825"),
new("Super Cup", "826"),
new("Crown Prince Cup", "827"),
new("Ligue 2", "828"),
new("Youth League", "829"),
new("Super Cup", "830"),
new("Super Cup", "831"),
new("Coupe de la Ligue", "832"),
new("Queensland Premier League", "833"),
new("South Australia State League 1", "834"),
new("New South Wales NPL 2", "835"),
new("Victoria NPL 2", "836"),
new("Rock Cup", "837"),
new("Super Cup", "838"),
new("Super Cup", "839"),
new("Taça Revelação U23", "840"),
new("QFA Cup", "841"),
new("Super Copa", "842"),
new("Copa Verde", "843"),
new("Ligue 1", "844"),
new("GFA League", "845"),
new("Somali Premier League", "846"),
new("Premier League", "847"),
new("UEFA Europa Conference League", "848"),
new("Baltic Cup", "849"),
new("UEFA U21 Championship - Qualification", "850"),
new("Carioca A2", "851"),
new("Super Cup", "852"),
new("Supercopa de Ecuador", "853"),
new("WE League", "854"),
new("Dhivehi Premier League", "855"),
new("CONCACAF Caribbean Club Championship", "856"),
new("Campeón de Campeones", "857"),
new("CONCACAF Gold Cup - Qualification", "858"),
new("COSAFA Cup", "859"),
new("Arab Cup", "860"),
new("U20 League", "861"),
new("3. Division", "862"),
new("Cup", "863"),
new("Supercopa", "864"),
new("Liga 3", "865"),
new("MLS All-Star", "866"),
new("Copa Paulino Alcantara", "867"),
new("Premier League", "868"),
new("CECAFA Club Cup", "869"),
new("Premier League", "870"),
new("Premier League Cup", "871"),
new("Liga Premier Serie B", "872"),
new("Thai Champions Cup", "873"),
new("Australia Cup", "874"),
new("Segunda División RFEF - Group 1", "875"),
new("Segunda División RFEF - Group 2", "876"),
new("Segunda División RFEF - Group 3", "877"),
new("Segunda División RFEF - Group 4", "878"),
new("Segunda División RFEF - Group 5", "879"),
new("World Cup - Women - Qualification Europe", "880"),
new("Olympics Men - Qualification Concacaf", "881"),
new("Olympics Women - Qualification Asia", "882"),
new("Reserve League", "883"),
new("Super Cup", "884"),
new("Campeones Cup", "885"),
new("UEFA U17 Championship - Qualification", "886"),
new("Second League", "887"),
new("Second League - Group B", "888"),
new("Second League - Group C", "889"),
new("U20 Elite League", "890"),
new("Coppa Italia Serie C", "891"),
new("Coppa Italia Serie D", "892"),
new("UEFA U19 Championship - Qualification", "893"),
new("Asian Cup Women - Qualification", "894"),
new("League Cup", "895"),
new("Super Cup", "896"),
new("Asian Cup Women", "897"),
new("League Cup", "898"),
new("League Cup", "899"),
new("Tipsport Malta Cup", "900"),
new("Ykköscup", "901"),
new("Algarve Cup", "902"),
new("The Atlantic Cup", "903"),
new("SheBelieves Cup", "904"),
new("Super Cup", "905"),
new("Reserve League", "906"),
new("Primera Division", "907"),
new("AFF U23 Championship", "908"),
new("MLS Next Pro", "909"),
new("Youth Viareggio Cup", "910"),
new("Southeast Asian Games", "911"),
new("CONCACAF Women U17", "912"),
new("CONMEBOL - UEFA Finalissima", "913"),
new("Tournoi Maurice Revello", "914"),
new("1. Division Women", "915"),
new("Kirin Cup", "916"),
new("Copa Ecuador", "917"),
new("UEFA U19 Championship - Women", "918"),
new("Mediterranean Games", "919"),
new("World Cup - U20 - Women", "920"),
new("UEFA U17 Championship", "921"),
new("Africa Cup of Nations - Women", "922"),
new("League 1 Ontario", "923"),
new("Piala Presiden", "924"),
new("Super Cup", "925"),
new("Copa America Femenina", "926"),
new("World Cup - Women - Qualification Concacaf", "927"),
new("AFF U19 Championship", "928"),
new("League Two", "929"),
new("Copa Uruguay", "930"),
new("Non League Premier - Southern Central", "931"),
new("Non League Div One - Northern East", "932"),
new("Non League Div One - Southern Central", "933"),
new("Arab Championship - U20", "934"),
new("Diski Shield", "935"),
new("Catarinense - 2", "936"),
new("Emirates Cup", "937"),
new("Oberliga - Bayern Nord", "938"),
new("Oberliga - Bayern Süd", "939"),
new("COTIF Tournament", "940"),
new("Islamic Solidarity Games", "941"),
new("Serie C - Girone B", "942"),
new("Serie C - Girone C", "943"),
new("Super Cup", "944"),
new("International Champions Cup - Women", "945"),
new("Second NL", "946"),
new("DFB Pokal - Women", "947"),
new("1a Divisão - Women", "948"),
new("CONMEBOL Libertadores Femenina", "949"),
new("World Cup - U17 - Women", "950"),
new("South American Youth Games", "951"),
new("AFC U23 Asian Cup - Qualification", "952"),
new("Africa U23 Cup of Nations - Qualification", "953"),
new("National League - Central", "954"),
new("National League - National", "955"),
new("National League - Northern", "956"),
new("National League - Southern", "957"),
new("Copa Costa Rica", "958"),
new("Cup", "959"),
new("Euro Championship - Qualification", "960"),
new("Supercopa", "961"),
new("Premier League", "962"),
new("CONCACAF U17", "963"),
new("Copa de la División Profesional", "964"),
new("AFC U20 Asian Cup", "965"),
new("Cup", "966"),
new("Cup", "967"),
new("Championnat D1", "968"),
new("Primeira Divisão", "969"),
new("CONMEBOL - U17", "970"),
new("Shield Cup", "971"),
new("Super Cup", "972"),
new("CAF Cup of Nations - U17", "973"),
new("Serie C - Supercoppa Lega Finals", "974"),
new("Serie C - Relegation - Play-offs", "975"),
new("Serie C - Promotion - Play-offs", "976"),
new("Tercera División RFEF - Promotion - Play-offs", "977"),
new("2nd Division - Play-offs", "978"),
new("Provincial - Play-offs VV", "979"),
new("Provincial - Play-offs ACFF", "980"),
new("Third Amateur Division - Play-offs", "981"),
new("Denmark Series - Promotion Round", "982"),
new("Denmark Series - Relegation Round", "983"),
new("National League - North - Play-offs", "984"),
new("National League - South - Play-offs", "985"),
new("Non League Div One - Play-offs", "986"),
new("U18 Premier League - Championship", "987"),
new("Oberliga - Promotion Round", "988"),
new("Oberliga - Relegation Round", "989"),
new("Gamma Ethniki - Promotion Group", "990"),
new("Campeonato de Portugal Prio - Promotion Round", "991"),
new("Football League - Championship", "992"),
new("Non League Premier - Isthmian - Play-offs", "993"),
new("Non League Premier - Northern - Play-offs", "994"),
new("Non League Premier - Southern South - Play-offs", "995"),
new("Non League Premier - Southern Central - Play-offs", "996"),
new("Serie D - Promotion - Play-offs", "997"),
new("Serie D - Relegation - Play-offs", "998"),
new("Serie D - Championship Round", "999"),
new("Segunda División RFEF - Play-offs", "1000"),
new("CONCACAF Women U20", "1001"),
new("Regionalliga - Promotion Play-offs", "1002"),
new("Regionalliga - Relegation Round", "1003"),
new("Derde Divisie - Relegation Round", "1004"),
new("1. Liga Classic - Play-offs", "1005"),
new("Primera División RFEF - Play Offs", "1006"),
new("3. Lig - Play-offs", "1007"),
new("CAFA Nations Cup", "1008"),
new("Liga III - Play-offs", "1009"),
new("3. liga - Promotion Play-off", "1010"),
new("Second Amateur Division - Play-offs ", "1011"),
new("AFC U17 Asian Cup", "1012"),
new("All-Island Cup - Women", "1013"),
new("Second League - Play-offs", "1014"),
new("CAF U23 Cup of Nations", "1015"),
new("CAC Games", "1016"),
new("U23 League", "1017"),
new("Federation Cup", "1018"),
new("Charity Shield", "1019"),
new("Calcutta Premier Division", "1020"),
new("Super Cup", "1021"),
new("Premier League - Summer Series", "1022"),
new("NB III - Southeast", "1023"),
new("UEFA - CONMEBOL - Club Challenge", "1024"),
new("Second League A - Fall Season Gold", "1025"),
new("Second League A - Fall Season Silver", "1026"),
new("3. Lig - Group 4", "1027"),
new("Concacaf Central American Cup", "1028"),
new("National 3 - Group G", "1029"),
new("Goiano - 2", "1030"),
new("Premier League", "1031"),
new("Copa de la Liga Profesional", "1032"),
new("Ekstraliga Women", "1033"),
new("2. Frauen Bundesliga", "1034"),
new("Copa Rio", "1035"),
new("Copa Santa Catarina", "1036"),
new("Paraibano 2", "1037"),
new("King's Cup", "1038"),
new("Premier League International Cup", "1039"),
new("UEFA Nations League - Women", "1040"),
new("Júniores U19", "1041"),
new("Super Cup", "1042"),
new("African Football League", "1043"),
new("Erste Liga Cup", "1044"),
new("Pan American Games", "1045"),
new("CONCACAF Gold Cup - Qualification - Women", "1046"),
new("Olympics Women - Qualification CAF", "1047"),
new("Premier Division", "1048"),
new("King's Cup", "1049"),
new("Super Cup", "1050"),
new("HKPL Cup", "1051"),
new("Kakkonen - Play-offs", "1052"),
new("Division 2 - Play-offs", "1053"),
new("2. Division - Play-offs", "1054"),
new("Ettan - Relegation Round", "1055"),
new("National League - Championship - Final", "1056"),
new("CONCACAF Gold Cup - Women", "1057"),
new("Supercopa Femenina", "1058"),
new("Recopa Catarinense", "1059"),
new("CONMEBOL - Pre-Olympic Tournament", "1060"),
new("Second League A - Spring Season Gold", "1061"),
new("Paulista - A4", "1062"),
new("Copa Alagoas", "1063"),
new("Second League A - Spring Season Silver", "1064"),
new("U19 League", "1065"),
new("CONCACAF U20 - Qualification", "1066"),
new("Torneo Promocional Amateur", "1067"),
new("FA Youth Cup", "1068"),
new("Goiano U20", "1069"),
new("AFC U20 Asian Cup - Women", "1070"),
new("Paranaense U20", "1071"),
new("All Africa Games", "1072"),
new("Baiano U20", "1073"),
new("SWPL Cup", "1074"),
new("Pro League A", "1075"),
new("Catarinense U20", "1076"),
new("WAFF Championship U23", "1077"),
new("SWF Scottish Cup", "1078"),
new("Yemeni League", "1079"),
new("Premier Division", "1080"),
new("CONMEBOL - U17 Femenino", "1081"),
new("Copa Rio U20", "1082"),
new("UEFA Championship - Women - Qualification", "1083"),
new("Championnat National", "1084"),
new("CONMEBOL U20 Femenino", "1085"),
new("Paulista - U20", "1086"),
new("Ykkösliiga", "1087"),
new("Pernambucano - U20", "1088"),
new("UAE-Qatar - Super Shield", "1089"),
new("NNSW League 1", "1090"),
new("Tasmania Northern Championship", "1091"),
new("Capital Territory NPL 2", "1092"),
new("Tasmania Southern Championship", "1093"),
new("Western Australia State League 1", "1094"),
new("USL League One Cup", "1095"),
new("Matogrossense 2", "1096"),
new("Copa Espírito Santo", "1097"),
new("Paulista Série B", "1098"),
new("Gamma Ethniki - Relegation Play-offs", "1099"),
new("Brasiliense U20", "1100"),
new("AFC U17 Asian Cup - Women", "1101"),
new("UEFA U17 Championship - Women", "1102"),
new("Premiership Women", "1103"),
new("Liga 3", "1104"),
new("Olympics - Intercontinental Play-offs", "1105"),
new("Carioca C", "1106"),
new("Mineiro U20", "1107"),
new("Sergipano U20", "1108"),
        };
LoadLogosAsync();
    }

    private async void LoadLogosAsync()
    {
        var tasks = new List<Task>();
        var semaphore = new SemaphoreSlim(25);
        foreach (var menuItemViewModel in Leagues)
        {
            tasks.Add(LoadSem(semaphore, menuItemViewModel));
        }

        await Task.WhenAll(tasks);
    }

    private static async Task LoadSem(SemaphoreSlim semaphore, MenuItemViewModel menuItemViewModel)
    {
        await semaphore.WaitAsync(); // Wait for a slot to become available
        try
        {
            await menuItemViewModel.LoadLogo();
        }
        finally
        {
            semaphore.Release(); // Release the slot when the task is completed
        }
    }

    #endregion

    #region ICommand

    public ICommand AllGamesCommand => new AsyncRelayCommand(AllGamesFetchData);

    #endregion

    #region ICommand Execution

    private async Task AllGamesFetchData()
    {
        // Switch current TabView to AllGamesTabView
        Ioc.Default.GetRequiredService<MainViewModel>().CurrentTabView = Ioc.Default.GetRequiredService<AllGamesTabViewModel>();

        await StartFetchingLiveGamesData();

        // TODO: Results and Fixtures
    }

    private async Task FetchLiveGamesDataAsync(CancellationToken cancellationToken)
    {
        while (!cancellationToken.IsCancellationRequested)
        {
            try
            {
                // Set loading state to true
                HelperFunctions.SetAllGamesLoadingProgressState(true);

                // Fetch Live Games data
                var liveGamesData = await _footballService.GetLiveGamesDataAsync();
                await RefreshLiveGames(JObject.Parse(liveGamesData));

                // Set loading state to false
                HelperFunctions.SetAllGamesLoadingProgressState(false);

                // Wait for the next interval
                await Task.Delay(60000, cancellationToken);
            }
            catch (OperationCanceledException)
            {
                // The operation was canceled, exit the method
                return;
            }
            catch (Exception)
            {
                // ignored
            }
        }
    }

    private async Task RefreshLiveGames(JObject jsonData)
    {
        var matchesCollection = await _deserializeDataService.DeserializeLiveGamesData(jsonData);

        var liveGamesViewModel = Ioc.Default.GetRequiredService<LiveGamesViewModel>();
        liveGamesViewModel.MatchesCollection = matchesCollection;
    }

    #endregion

    public async Task StartFetchingLiveGamesData()
    {
        _fetchLiveGamesDataCancellationTokenSource = new CancellationTokenSource();

        await FetchLiveGamesDataAsync(_fetchLiveGamesDataCancellationTokenSource.Token);
    }

    public void StopFetchingLiveGamesData()
    {
        _fetchLiveGamesDataCancellationTokenSource?.Cancel();
    }
}